### ISSUE TITLE
Couldn't load native library in tests

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#688]
**Description:**
$Subject
Coming from docker-java library.
```
java.io.IOException: Couldn't load native library
at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:56)
at org.newsclub.net.unix.AFUNIXSocket.(AFUNIXSocket.java:48)
at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:77)
at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:72)
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment]
Due to the library being deprecated.
